global using System.Text.RegularExpressions;
global using MonkeyCache;
global using System.Text.Json;
global using KlioMobile.Framework.Extensions;
global using KlioMobile.Framework.Exceptions;
global using System.Text;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using CommunityToolkit.Mvvm.ComponentModel;
